"""
Cases router — full CRUD + multipart file upload + queued analysis.

Analysis is no longer run by this process. POST /cases hashes the upload,
asks the Redis cache whether that exact content has been analysed before, and
either replays the stored verdict immediately or publishes a Celery message
and returns. See app/queue/ for the orchestration itself.
"""

from __future__ import annotations

import json
import os
import uuid
from pathlib import Path
from typing import Optional

import aiosqlite
from fastapi import (
    APIRouter,
    File,
    Form,
    HTTPException,
    Query,
    UploadFile,
)

from app.database import get_db
from app.models import (
    CaseListResponse,
    CaseResponse,
    CaseUpdate,
    DashboardStats,
)
from app.queue import cache, state
from app.queue.redis_client import BrokerUnavailable, require as require_broker
from app.queue.tasks import MAX_ATTEMPTS, analyze_case
from app.services.analyser import validate_file

router = APIRouter()

UPLOAD_DIR = Path(os.getenv("UPLOAD_DIR", "uploads"))
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
BASE_URL = os.getenv("BASE_URL", "http://localhost:8000")


# ── Helpers ──────────────────────────────────────────────────────────────────

def _row_to_dict(row: aiosqlite.Row) -> dict:
    return dict(row)


def _build_response(row: dict, results: list[dict] | None = None,
                    job: dict | None = None) -> dict:
    """Map snake_case DB row → camelCase CaseResponse dict.

    `job` is the live queue record from Redis. It is attached to every case
    response rather than exposed only on a separate endpoint so a client that
    already polls `GET /cases/{id}` learns it is third in line without making
    a second request. It is None for cases older than the queue's retention,
    and clients must treat its absence as "no queue information" rather than
    an error.
    """
    return {
        "id": row["id"],
        "caseId": row["case_id"],
        "title": row["title"],
        "mediaType": row["media_type"],
        "status": row["status"],
        "riskScore": row["risk_score"],
        "syntheticLikelihood": row["synthetic_likelihood"],
        "fileName": row.get("file_name"),
        "fileUrl": row.get("file_url"),
        "fileSize": row.get("file_size"),
        "userId": row.get("user_id"),
        "notes": row.get("notes"),
        "createdAt": row.get("created_at"),
        "updatedAt": row.get("updated_at"),
        "analysisResults": results or [],
        "job": job,
    }


async def _fetch_analysis(db: aiosqlite.Connection, case_db_id: str) -> list[dict]:
    async with db.execute(
        "SELECT * FROM analysis_results WHERE case_id = ? ORDER BY created_at",
        (case_db_id,),
    ) as cur:
        rows = await cur.fetchall()
    return [
        {
            "id": r["id"],
            "case_id": r["case_id"],
            "model_name": r["model_name"],
            "confidence": r["confidence"],
            "label": r["label"],
            "details": json.loads(r["details"]) if r["details"] else None,
            "created_at": r["created_at"],
        }
        for r in rows
    ]


# ── Cache replay ──────────────────────────────────────────────────────────────

async def _replay_cached(case_db_id: str, payload: dict) -> None:
    """Write a previously computed verdict onto a brand-new case.

    This is the whole point of the cache: the rows go straight into
    analysis_results and the case is terminal before the HTTP response is even
    sent, so a resubmitted file is answered in milliseconds instead of
    minutes. Row ids are regenerated by `cache.rehydrate_rows` — reusing the
    original case's ids would violate the analysis_results primary key on the
    second replay.
    """
    rows = cache.rehydrate_rows(payload, case_db_id)

    db = await get_db()
    try:
        await db.execute("PRAGMA foreign_keys=ON;")
        await db.execute(
            """
            UPDATE cases
               SET status = ?, risk_score = ?, synthetic_likelihood = ?,
                   updated_at = datetime('now')
             WHERE id = ?
            """,
            (payload["status"], payload["risk"], payload["likelihood"], case_db_id),
        )
        for r in rows:
            await db.execute(
                """
                INSERT INTO analysis_results
                    (id, case_id, model_name, confidence, label, details)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (r["id"], case_db_id, r["model_name"], r["confidence"],
                 r["label"], r["details"]),
            )
        await db.commit()
    finally:
        await db.close()

    print(f"[Cache HIT] case={case_db_id} status={payload['status']} "
          f"(originally computed for {payload.get('sourceCaseId')})")


# ── Routes ────────────────────────────────────────────────────────────────────

@router.get("/cases", response_model=CaseListResponse)
async def list_cases(
    page: int = Query(1, ge=1),
    page_size: int = Query(20, ge=1, le=100),
    media_type: Optional[str] = Query(None),
    status: Optional[str] = Query(None),
    q: Optional[str] = Query(None, description="Search title"),
):
    """Return a paginated list of all cases."""
    filters, params = [], []

    if media_type:
        filters.append("media_type = ?")
        params.append(media_type)
    if status:
        filters.append("status = ?")
        params.append(status)
    if q:
        filters.append("title LIKE ?")
        params.append(f"%{q}%")

    where = ("WHERE " + " AND ".join(filters)) if filters else ""
    offset = (page - 1) * page_size

    db = await get_db()
    try:
        async with db.execute(f"SELECT COUNT(*) FROM cases {where}", params) as cur:
            total = (await cur.fetchone())[0]

        async with db.execute(
            f"""
            SELECT * FROM cases {where}
            ORDER BY created_at DESC
            LIMIT ? OFFSET ?
            """,
            params + [page_size, offset],
        ) as cur:
            rows = await cur.fetchall()

        # Queue state is only read for cases that could still be in the queue.
        # Attaching it to every settled case on every page would cost two
        # Redis round trips per row to report "finished" for rows whose
        # `status` already says so.
        cases = []
        for r in rows:
            d = _row_to_dict(r)
            job = state.get_job(d["id"]) if d["status"] == "processing" else None
            cases.append(_build_response(d, job=job))
    finally:
        await db.close()

    return {"cases": cases, "total": total, "page": page, "page_size": page_size}


@router.post("/cases", response_model=CaseResponse, status_code=201)
async def create_case(
    title: str = Form(...),
    media_type: str = Form(...),
    user_id: Optional[str] = Form(None),
    notes: Optional[str] = Form(None),
    source_url: Optional[str] = Form(
        None,
        description="Page-media URL this file was captured from. Used as a "
                    "secondary cache key by the browser extension.",
    ),
    file: UploadFile = File(...),
):
    """
    Create a new forensic case.
    Accepts multipart/form-data with the evidence file.

    Three outcomes, all returning 201 with the case:
      * cache hit  — the verdict is already attached, status is terminal
      * queued     — a Celery job was published, status is `processing`
      * 503        — the broker is unreachable and nothing was accepted
    """
    # ── Validate ──────────────────────────────────────────────────────────────
    if media_type not in ("image", "video", "audio"):
        raise HTTPException(400, "media_type must be one of: image, video, audio")

    content = await file.read()
    error = validate_file(media_type, file.content_type or "", len(content))
    if error:
        raise HTTPException(422, error)

    # ── Broker check, before anything is written ─────────────────────────────
    # Refusing here rather than after the insert means a rejected upload
    # leaves no orphaned 'processing' case that nothing will ever pick up.
    # The cache read below needs Redis anyway, so this single check covers
    # both paths.
    try:
        require_broker()
    except BrokerUnavailable as exc:
        raise HTTPException(503, str(exc)) from exc

    # ── Cache lookup, before the file is even stored ─────────────────────────
    sha = cache.content_hash(content)
    cached = cache.lookup(media_type, sha)

    # ── Persist file ──────────────────────────────────────────────────────────
    ext = Path(file.filename or "upload").suffix or ".bin"
    safe_name = f"{uuid.uuid4().hex}{ext}"
    file_path = UPLOAD_DIR / safe_name
    file_path.write_bytes(content)
    file_url = f"{BASE_URL}/uploads/{safe_name}"

    # ── Write case row ────────────────────────────────────────────────────────
    case_id = f"CASE-{uuid.uuid4().hex[:8].upper()}"
    db_id = str(uuid.uuid4())

    db = await get_db()
    try:
        await db.execute("PRAGMA foreign_keys=ON;")
        await db.execute(
            """
            INSERT INTO cases
                (id, case_id, title, media_type, status, risk_score,
                 synthetic_likelihood, file_name, file_url, file_size, user_id, notes)
            VALUES (?, ?, ?, ?, 'processing', 0, 0, ?, ?, ?, ?, ?)
            """,
            (db_id, case_id, title, media_type,
             file.filename, file_url, len(content), user_id, notes),
        )
        await db.commit()
    finally:
        await db.close()

    # Remember which URL these bytes came from even when the analysis has yet
    # to run, so the extension's next visit to the same page resolves.
    if source_url:
        cache.remember_url(source_url, sha)

    # ── Hit: replay and return, no worker involved ───────────────────────────
    if cached:
        await _replay_cached(db_id, cached)
        state.mark_cached(db_id, case_id=case_id, media_type=media_type,
                          content_hash=sha, source_url=source_url or "")
    else:
        # ── Miss: hand it to a worker ────────────────────────────────────────
        try:
            async_result = analyze_case.delay(db_id, media_type, str(file_path),
                                              sha, source_url or "")
        except Exception as exc:  # noqa: BLE001 — kombu raises its own family
            # Redis answered `ping` a moment ago but would not take the
            # message. The case row already exists, so mark it failed rather
            # than leaving it 'processing' forever with no job behind it.
            await _mark_case_failed(db_id)
            raise HTTPException(
                503,
                f"Could not queue the analysis job: {exc}. The case was "
                f"recorded as failed; resubmit once the queue is healthy.",
            ) from exc

        state.mark_queued(db_id, case_id=case_id, media_type=media_type,
                          celery_task_id=async_result.id,
                          max_attempts=MAX_ATTEMPTS,
                          content_hash=sha, source_url=source_url or "")

    # Re-read so the response carries whatever the cache replay just wrote.
    db = await get_db()
    try:
        async with db.execute("SELECT * FROM cases WHERE id = ?", (db_id,)) as cur:
            row = _row_to_dict(await cur.fetchone())
        results = await _fetch_analysis(db, db_id)
    finally:
        await db.close()

    return _build_response(row, results, state.get_job(db_id))


async def _mark_case_failed(case_db_id: str) -> None:
    db = await get_db()
    try:
        await db.execute(
            "UPDATE cases SET status='failed', updated_at=datetime('now') WHERE id=?",
            (case_db_id,),
        )
        await db.commit()
    finally:
        await db.close()


@router.get("/cases/{case_id}", response_model=CaseResponse)
async def get_case(case_id: str):
    """Fetch a single case including its analysis results."""
    db = await get_db()
    try:
        async with db.execute("SELECT * FROM cases WHERE case_id = ?", (case_id,)) as cur:
            row = await cur.fetchone()
        if row is None:
            raise HTTPException(404, f"Case '{case_id}' not found.")
        row_dict = _row_to_dict(row)
        results = await _fetch_analysis(db, row_dict["id"])
    finally:
        await db.close()

    return _build_response(row_dict, results, state.get_job(row_dict["id"]))


@router.patch("/cases/{case_id}", response_model=CaseResponse)
async def update_case(case_id: str, body: CaseUpdate):
    """Partially update a case (title, status, scores, notes)."""
    db = await get_db()
    try:
        async with db.execute("SELECT id FROM cases WHERE case_id = ?", (case_id,)) as cur:
            found = await cur.fetchone()
            if found is None:
                raise HTTPException(404, f"Case '{case_id}' not found.")
            internal_id = found["id"]

        updates, vals = [], []
        if body.title is not None:
            updates.append("title = ?"); vals.append(body.title)
        if body.status is not None:
            updates.append("status = ?"); vals.append(body.status)
        if body.risk_score is not None:
            updates.append("risk_score = ?"); vals.append(body.risk_score)
        if body.synthetic_likelihood is not None:
            updates.append("synthetic_likelihood = ?"); vals.append(body.synthetic_likelihood)
        if body.notes is not None:
            updates.append("notes = ?"); vals.append(body.notes)

        if updates:
            updates.append("updated_at = datetime('now')")
            await db.execute(
                f"UPDATE cases SET {', '.join(updates)} WHERE id = ?",
                vals + [internal_id],
            )
            await db.commit()

        async with db.execute("SELECT * FROM cases WHERE id = ?", (internal_id,)) as cur:
            row = _row_to_dict(await cur.fetchone())
        results = await _fetch_analysis(db, internal_id)
    finally:
        await db.close()

    return _build_response(row, results, state.get_job(internal_id))


@router.delete("/cases/{case_id}", status_code=204)
async def delete_case(case_id: str):
    """Permanently delete a case and its analysis results."""
    db = await get_db()
    try:
        async with db.execute("SELECT id, file_url FROM cases WHERE case_id = ?", (case_id,)) as cur:
            row = await cur.fetchone()
        if row is None:
            raise HTTPException(404, f"Case '{case_id}' not found.")

        # Remove uploaded file
        if row["file_url"]:
            fname = row["file_url"].split("/uploads/")[-1]
            fpath = UPLOAD_DIR / fname
            if fpath.exists():
                fpath.unlink(missing_ok=True)

        await db.execute("DELETE FROM cases WHERE id = ?", (row["id"],))
        await db.commit()
    finally:
        await db.close()


@router.get("/stats", response_model=DashboardStats)
async def get_stats():
    """Aggregate dashboard statistics."""
    db = await get_db()
    try:
        async with db.execute(
            """
            SELECT
                COUNT(*) AS total,
                SUM(CASE WHEN status='authentic'   THEN 1 ELSE 0 END) AS authentic,
                SUM(CASE WHEN status='manipulated' THEN 1 ELSE 0 END) AS manipulated,
                SUM(CASE WHEN status='processing'  THEN 1 ELSE 0 END) AS processing,
                AVG(risk_score) AS avg_risk
            FROM cases
            """
        ) as cur:
            r = dict(await cur.fetchone())
    finally:
        await db.close()

    return {
        "totalCases": r["total"] or 0,
        "authentic": r["authentic"] or 0,
        "manipulated": r["manipulated"] or 0,
        "processing": r["processing"] or 0,
        "avgRiskScore": round(r["avg_risk"] or 0, 1),
    }
